### ISSUE TITLE
Transformation abstractions

### ISSUE THREAD

**Issue by aldesantis** [pragmarb/pragma-migration#4]
### Todos

- [ ] Abstraction to deal with decorators/contracts directly
  - [ ] Class-based pattern matching (in `Base#apply_to`)
  - [ ] `Base#add_property`, `Base#transform_property` etc.
- [ ] Figure out how to apply migrations on collections (e.g. `Base.migrate_each`?)

### Notes

Not sure this is doable/we want to do it.
